name       : cubicsdr
version    : 0.2.3
release    : 3
source     :
    - https://github.com/cjcliffe/CubicSDR/archive/0.2.3.tar.gz : b058883a82c466530000ec15aa6c7f690036efb0374ca4da87da441fbd2043cf
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-Platform Software-Defined Radio Application
description: |
    CubicSDR is a Software-Defined Radio application which allows you to navigate the radio spectrum and demodulate any signals you might discover.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(SoapySDR)
    - liquid-dsp-devel
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
