name       : cubicsdr
version    : 0.2.7
release    : 8
source     :
    - https://github.com/cjcliffe/CubicSDR/archive/refs/tags/0.2.7.tar.gz : 790f851e08f1068081a8593dfd4a149c7414e7d70c1f5cafd287331df493b811
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Cross-Platform Software-Defined Radio Application
description: |
    CubicSDR is a Software-Defined Radio application which allows you to navigate the radio spectrum and demodulate any signals you might discover.
builddeps  :
    - pkgconfig(SoapySDR)
    - pkgconfig(gl)
    - pkgconfig(libpulse)
    - pkgconfig(x11)
    - liquid-dsp-devel
    - wxwidgets-devel
rundeps    :
    - soapyrtlsdr
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
